// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
// ERROR
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// BOOK
export const BOOK_LOADING = 'BOOK_LOADING';
export const GET_BOOK = 'GET_BOOK';
export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_BY_GENRES = 'GET_BY_GENRES';
export const GET_AUTOCOMPLETE = 'GET_AUTOCOMPLETE';
export const SEARCH_BOOKS = 'SEARCH_BOOKS';

//CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_ALL_FROM_CART = 'DELETE_ALL_FROM_CART';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CHECKOUT = 'CHECKOUT';

//CHECKOUT_CONFIRM
export const CHECKOUT_CONFIRM = 'CHECKOUT_CONFIRM';

//ORDERS
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const ORDER_LOADING = 'ORDER_LOADING';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';

//statistic
export const COUNT_USER = 'COUNT_USER';
export const COUNT_MONEY = 'COUNT_MONEY';
export const SET_LOOK_UP_USER = 'SET_LOOK_UP_USER';
export const CLEAR_LOOK_UP_USER = 'CLEAR_LOOK_UP_USER';
